spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testapiswagger?useUnicode=yes&characterEncoding=UTF-8&characterSetResults=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false


#spring:
#      thymeleaf:
#        cache: false
#        prefix: classpath:/templates
server:
  port: 8081
zuul:
  routes:
    foos:
      path: /authors/**
      url: https://newiosapi.herokuapp.com/rest/authors

