spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/testapiswagger
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 1
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false


#spring:
#      thymeleaf:
#        cache: false
#        prefix: classpath:/templates
server:
  port: 8080
zuul:
  routes:
    foos:
      path: /authors/**
      url: https://newiosapi.herokuapp.com/rest/authors

